# PCA Dimensionality Reduction Configuration for AdaptFoundation Project
# ========================================================================

# Foundation Models to Process
models:
  - dinov2_vits14    # Small: 1152D → reduced
  - dinov2_vitb14    # Base: 2304D → reduced
  - dinov2_vitl14    # Large: 3072D → reduced
  - dinov2_vitg14    # Giant: 4608D → reduced

# Feature Configurations to Apply PCA
configurations:
  - multi_axes_average    # Primary configuration for comparison
  - multi_axes_max        # Alternative pooling strategies
  - multi_axes_add        # Alternative pooling strategies
  - single_axis_axial     # Individual axis analysis
  - single_axis_coronal   # Individual axis analysis
  - single_axis_sagittal  # Individual axis analysis

# PCA Reduction Modes
pca_modes:
  # Champollion comparison modes
  - mode: "fixed"
    n_components: 32
    description: "PCA 32D (Champollion V1 comparison)"
    
  - mode: "fixed"
    n_components: 256
    description: "PCA 256D (Champollion V0 comparison)"
    
  # Variance-based mode
  - mode: "variance"
    variance_threshold: 0.95
    description: "PCA 95% variance (adaptive dimensionality)"

# Data Configuration
data:
  features_base_path: "feature_extracted"
  
# Processing Configuration
processing:
  sequential_models: true        # Process models sequentially to avoid memory issues
  sequential_configs: true       # Process configurations sequentially
  skip_existing: false          # Re-process even if PCA files exist
  
# Validation and Quality Control
validation:
  check_feature_files: true     # Verify source feature files exist
  validate_dimensions: true     # Check expected input/output dimensions
  save_metadata: true          # Save detailed PCA metadata
  
# Output Configuration
output:
  save_individual: true        # Save PCA files in individual config directories
  save_summary: true          # Save processing summary
  detailed_logging: true      # Detailed progress output

# Advanced Configuration (for fine-tuning)
advanced:
  # Memory optimization
  batch_processing: false      # Process in batches (if memory limited)
  cleanup_intermediate: false  # Clean intermediate files
  
  # Additional PCA modes (experimental)
  experimental_modes: []
  
  # Custom variance thresholds
  custom_thresholds: []        # e.g., [0.90, 0.99]
  
  # Custom fixed components
  custom_components: []        # e.g., [64, 128, 512]